FROM jenkins/jenkins:latest
USER root
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get update && \
    apt-get install -y nodejs && \
    apt-get install -y npm
RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common
RUN curl -fsSL https://get.docker.com | sh
RUN apt-get clean && \
    rm -fr /var/lib/apt/lists/*
USER jenkins
